# Generated by Django 6.0 on 2026-01-05 15:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage/Fixed Discount'), ('BUY_X_GET_Y', 'Buy X Get Y Discount')], help_text='Loại chiến lược giảm giá sẽ áp dụng', max_length=20)),
                ('code', models.CharField(help_text='Mã khuyến mãi', max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Promotion Base',
            },
        ),
        migrations.CreateModel(
            name='PercentageDiscount',
            fields=[
                ('promotionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promotions.promotionbase')),
                ('value', models.DecimalField(decimal_places=2, help_text='Giá trị giảm giá (ví dụ: 0.10 cho 10% hoặc 50000 VND)', max_digits=10)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền đơn hàng tối thiểu để áp dụng', max_digits=10)),
            ],
            options={
                'verbose_name': 'Percentage/Fixed Promotion',
                'verbose_name_plural': 'Percentage/Fixed Promotions',
            },
            bases=('promotions.promotionbase',),
        ),
        migrations.CreateModel(
            name='BuyXGetYDiscount',
            fields=[
                ('promotionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promotions.promotionbase')),
                ('buy_quantity', models.PositiveIntegerField(help_text='Số lượng mua tối thiểu (X)')),
                ('get_quantity', models.PositiveIntegerField(help_text='Số lượng tặng (Y)')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion', to='products.product')),
            ],
            options={
                'verbose_name': 'Buy X Get Y Promotion',
                'verbose_name_plural': 'Buy X Get Y Promotions',
            },
            bases=('promotions.promotionbase',),
        ),
        migrations.CreateModel(
            name='PercentageDiscountProduct',
            fields=[
                ('promotionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promotions.promotionbase')),
                ('value', models.DecimalField(decimal_places=2, help_text='Giá trị giảm giá (ví dụ: 0.10 cho 10% hoặc 50000 VND)', max_digits=10)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền đơn hàng tối thiểu để áp dụng', max_digits=10)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='products.product')),
            ],
            options={
                'verbose_name': 'Percentage/Fixed Promotion',
                'verbose_name_plural': 'Percentage/Fixed Promotions',
            },
            bases=('promotions.promotionbase',),
        ),
    ]
