# Generated by Django 5.2.8 on 2026-01-04 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã định danh (VD: VNPAY, MOMO, COD)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên hiển thị (VD: Ví VNPAY)', max_length=100)),
                ('icon_url', models.CharField(blank=True, help_text='Link icon hoặc dùng path static', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Bật/Tắt phương thức này')),
                ('order_display', models.IntegerField(default=0, help_text='Thứ tự hiển thị trên web')),
            ],
            options={
                'verbose_name': 'Phương thức thanh toán',
                'ordering': ['order_display'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('providerReference', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('paidAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
        ),
    ]
