# Generated by Django 6.0 on 2026-01-05 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('stock_qty', models.IntegerField(default=0)),
                ('images', models.CharField(blank=True, max_length=500, null=True)),
                ('attributes', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('unit', models.CharField(default='pack', max_length=20)),
                ('sold', models.IntegerField(default=0)),
                ('weight_per_unit', models.FloatField(default=0.0)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('manufacturing_date', models.DateTimeField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('is_perishable', models.BooleanField(default=False)),
                ('rating_average', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(default=list)),
                ('featured', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=0.0)),
                ('dimensions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category')),
            ],
        ),
    ]
