# Generated by Django 5.2.8 on 2026-01-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
